# Generated by Django 5.2.5 on 2025-09-01 19:50

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Banca')),
                ('valor_inicial', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Inicial (R$)')),
                ('ativa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banca_inicial', models.DecimalField(decimal_places=2, default=Decimal('250.00'), max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Aposta')),
                ('evento', models.CharField(max_length=200, verbose_name='Evento Esportivo')),
                ('mercado', models.CharField(max_length=100, verbose_name='Mercado/Tipo de Aposta')),
                ('odd', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Odd')),
                ('valor_apostado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Apostado (R$)')),
                ('resultado', models.CharField(choices=[('GREEN', 'Green'), ('RED', 'Red'), ('VOID', 'Anulada'), ('PENDING', 'Pendente')], default='PENDING', max_length=10)),
                ('retorno', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='Lucro/Prejuízo (R$)')),
                ('banca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apostas', to='app_analise.banca')),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='app_analise.liga')),
            ],
            options={
                'unique_together': {('liga', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id_jogo', models.IntegerField(primary_key=True, serialize=False)),
                ('rodada', models.CharField(blank=True, max_length=100, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('placar_casa_1t', models.IntegerField(default=0)),
                ('placar_fora_1t', models.IntegerField(default=0)),
                ('placar_casa_2t', models.IntegerField(default=0)),
                ('placar_fora_2t', models.IntegerField(default=0)),
                ('placar_casa_total', models.IntegerField(default=0)),
                ('placar_fora_total', models.IntegerField(default=0)),
                ('finalizacao_casa_1t', models.IntegerField(default=0)),
                ('finalizacao_fora_1t', models.IntegerField(default=0)),
                ('finalizacao_casa_2t', models.IntegerField(default=0)),
                ('finalizacao_fora_2t', models.IntegerField(default=0)),
                ('finalizacao_casa_total', models.IntegerField(default=0)),
                ('finalizacao_fora_total', models.IntegerField(default=0)),
                ('chutes_no_gol_casa_1t', models.IntegerField(default=0)),
                ('chutes_no_gol_fora_1t', models.IntegerField(default=0)),
                ('chutes_no_gol_casa_2t', models.IntegerField(default=0)),
                ('chutes_no_gol_fora_2t', models.IntegerField(default=0)),
                ('chutes_no_gol_casa_total', models.IntegerField(default=0)),
                ('chutes_no_gol_fora_total', models.IntegerField(default=0)),
                ('escanteios_casa_1t', models.IntegerField(default=0)),
                ('escanteios_fora_1t', models.IntegerField(default=0)),
                ('escanteios_casa_2t', models.IntegerField(default=0)),
                ('escanteios_fora_2t', models.IntegerField(default=0)),
                ('escanteios_casa_total', models.IntegerField(default=0)),
                ('escanteios_fora_total', models.IntegerField(default=0)),
                ('cartoes_amarelos_casa_1t', models.IntegerField(default=0)),
                ('cartoes_amarelos_fora_1t', models.IntegerField(default=0)),
                ('cartoes_amarelos_casa_2t', models.IntegerField(default=0)),
                ('cartoes_amarelos_fora_2t', models.IntegerField(default=0)),
                ('cartoes_amarelos_casa_total', models.IntegerField(default=0)),
                ('cartoes_amarelos_fora_total', models.IntegerField(default=0)),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_analise.liga')),
                ('time_casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos_casa', to='app_analise.time')),
                ('time_fora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos_fora', to='app_analise.time')),
            ],
        ),
        migrations.CreateModel(
            name='AnaliseTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jogos_total', models.IntegerField(default=0)),
                ('jogos_casa', models.IntegerField(default=0)),
                ('jogos_fora', models.IntegerField(default=0)),
                ('media_placar_casa_1t', models.FloatField(default=0.0)),
                ('media_placar_fora_1t', models.FloatField(default=0.0)),
                ('media_placar_casa_2t', models.FloatField(default=0.0)),
                ('media_placar_fora_2t', models.FloatField(default=0.0)),
                ('media_placar_casa_total', models.FloatField(default=0.0)),
                ('media_placar_fora_total', models.FloatField(default=0.0)),
                ('media_placar_geral_1t', models.FloatField(default=0.0)),
                ('media_placar_geral_2t', models.FloatField(default=0.0)),
                ('media_placar_geral_total', models.FloatField(default=0.0)),
                ('media_finalizacao_casa_1t', models.FloatField(default=0.0)),
                ('media_finalizacao_fora_1t', models.FloatField(default=0.0)),
                ('media_finalizacao_casa_2t', models.FloatField(default=0.0)),
                ('media_finalizacao_fora_2t', models.FloatField(default=0.0)),
                ('media_finalizacao_casa_total', models.FloatField(default=0.0)),
                ('media_finalizacao_fora_total', models.FloatField(default=0.0)),
                ('media_finalizacao_geral_1t', models.FloatField(default=0.0)),
                ('media_finalizacao_geral_2t', models.FloatField(default=0.0)),
                ('media_finalizacao_geral_total', models.FloatField(default=0.0)),
                ('media_chutes_no_gol_casa_1t', models.FloatField(default=0.0)),
                ('media_chutes_no_gol_fora_1t', models.FloatField(default=0.0)),
                ('media_chutes_no_gol_casa_2t', models.FloatField(default=0.0)),
                ('media_chutes_no_gol_fora_2t', models.FloatField(default=0.0)),
                ('media_chutes_no_gol_casa_total', models.FloatField(default=0.0)),
                ('media_chutes_no_gol_fora_total', models.FloatField(default=0.0)),
                ('media_chutes_no_gol_geral_1t', models.FloatField(default=0.0)),
                ('media_chutes_no_gol_geral_2t', models.FloatField(default=0.0)),
                ('media_chutes_no_gol_geral_total', models.FloatField(default=0.0)),
                ('media_escanteios_casa_1t', models.FloatField(default=0.0)),
                ('media_escanteios_fora_1t', models.FloatField(default=0.0)),
                ('media_escanteios_casa_2t', models.FloatField(default=0.0)),
                ('media_escanteios_fora_2t', models.FloatField(default=0.0)),
                ('media_escanteios_casa_total', models.FloatField(default=0.0)),
                ('media_escanteios_fora_total', models.FloatField(default=0.0)),
                ('media_escanteios_geral_1t', models.FloatField(default=0.0)),
                ('media_escanteios_geral_2t', models.FloatField(default=0.0)),
                ('media_escanteios_geral_total', models.FloatField(default=0.0)),
                ('media_cartoes_amarelos_casa_1t', models.FloatField(default=0.0)),
                ('media_cartoes_amarelos_fora_1t', models.FloatField(default=0.0)),
                ('media_cartoes_amarelos_casa_2t', models.FloatField(default=0.0)),
                ('media_cartoes_amarelos_fora_2t', models.FloatField(default=0.0)),
                ('media_cartoes_amarelos_casa_total', models.FloatField(default=0.0)),
                ('media_cartoes_amarelos_fora_total', models.FloatField(default=0.0)),
                ('media_cartoes_amarelos_geral_1t', models.FloatField(default=0.0)),
                ('media_cartoes_amarelos_geral_2t', models.FloatField(default=0.0)),
                ('media_cartoes_amarelos_geral_total', models.FloatField(default=0.0)),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_analise.liga')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_analise.time')),
            ],
            options={
                'unique_together': {('liga', 'time')},
            },
        ),
    ]
