# Generated by Django 5.2.5 on 2025-09-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_analise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aposta',
            name='detalhes_multipla',
            field=models.TextField(blank=True, null=True, verbose_name='Detalhes da Múltipla'),
        ),
        migrations.AddField(
            model_name='aposta',
            name='is_multipla',
            field=models.BooleanField(default=False, verbose_name='É uma aposta múltipla?'),
        ),
    ]
