# Generated by Django 5.2.5 on 2025-09-07 19:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_analise', '0002_aposta_detalhes_multipla_aposta_is_multipla'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analisetime',
            old_name='jogos_total',
            new_name='jogos',
        ),
        migrations.AlterUniqueTogether(
            name='analisetime',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='time',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='jogo',
            name='id_jogo',
        ),
        migrations.AddField(
            model_name='jogo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='analisetime',
            name='liga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_analise.liga'),
        ),
        migrations.AlterField(
            model_name='analisetime',
            name='time',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app_analise.time'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='cartoes_amarelos_casa_1t',
            field=models.IntegerField(default=0, verbose_name='Cartões Amarelos Casa 1T'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='cartoes_amarelos_casa_2t',
            field=models.IntegerField(default=0, verbose_name='Cartões Amarelos Casa 2T'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='cartoes_amarelos_fora_1t',
            field=models.IntegerField(default=0, verbose_name='Cartões Amarelos Fora 1T'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='cartoes_amarelos_fora_2t',
            field=models.IntegerField(default=0, verbose_name='Cartões Amarelos Fora 2T'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='chutes_no_gol_casa_1t',
            field=models.IntegerField(default=0, verbose_name='Chutes no Gol Casa 1T'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='chutes_no_gol_casa_2t',
            field=models.IntegerField(default=0, verbose_name='Chutes no Gol Casa 2T'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='chutes_no_gol_fora_1t',
            field=models.IntegerField(default=0, verbose_name='Chutes no Gol Fora 1T'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='chutes_no_gol_fora_2t',
            field=models.IntegerField(default=0, verbose_name='Chutes no Gol Fora 2T'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='data',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data do Jogo'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='escanteios_casa_1t',
            field=models.IntegerField(default=0, verbose_name='Escanteios Casa 1T'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='escanteios_casa_2t',
            field=models.IntegerField(default=0, verbose_name='Escanteios Casa 2T'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='escanteios_fora_1t',
            field=models.IntegerField(default=0, verbose_name='Escanteios Fora 1T'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='escanteios_fora_2t',
            field=models.IntegerField(default=0, verbose_name='Escanteios Fora 2T'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='finalizacao_casa_1t',
            field=models.IntegerField(default=0, verbose_name='Finalizações Casa 1T'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='finalizacao_casa_2t',
            field=models.IntegerField(default=0, verbose_name='Finalizações Casa 2T'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='finalizacao_fora_1t',
            field=models.IntegerField(default=0, verbose_name='Finalizações Fora 1T'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='finalizacao_fora_2t',
            field=models.IntegerField(default=0, verbose_name='Finalizações Fora 2T'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='liga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_analise.liga', verbose_name='Liga'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='placar_casa_1t',
            field=models.IntegerField(default=0, verbose_name='Placar Casa 1T'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='placar_casa_2t',
            field=models.IntegerField(default=0, verbose_name='Placar Casa 2T'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='placar_fora_1t',
            field=models.IntegerField(default=0, verbose_name='Placar Fora 1T'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='placar_fora_2t',
            field=models.IntegerField(default=0, verbose_name='Placar Fora 2T'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='rodada',
            field=models.IntegerField(default=0, verbose_name='Rodada'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='time_casa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos_casa', to='app_analise.time', verbose_name='Time da Casa'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='time_fora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos_fora', to='app_analise.time', verbose_name='Time de Fora'),
        ),
        migrations.AlterField(
            model_name='liga',
            name='nome',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome da Liga'),
        ),
        migrations.AlterField(
            model_name='time',
            name='liga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='app_analise.liga', verbose_name='Liga'),
        ),
        migrations.AlterField(
            model_name='time',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do Time'),
        ),
        migrations.RemoveField(
            model_name='analisetime',
            name='id',
        ),
    ]
