# Generated by Django 5.2.5 on 2025-09-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_analise', '0003_rename_jogos_total_analisetime_jogos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aposta',
            name='evento',
            field=models.CharField(max_length=80, verbose_name='Evento Esportivo'),
        ),
    ]
